# CodeRabbit Configuration for JXCT Soil Sensor Project
# Максимально полезное ревью - неограниченные комментарии, без изменений кода

# Основные настройки
review:
  # Анализ только изменённых файлов
  diff_only: true

  # Детальные проверки для максимальной пользы
  checks:
    - name: "Code Quality"
      description: "Детальная проверка качества кода"
      severity: "info"

    - name: "Security"
      description: "Комплексная проверка безопасности"
      severity: "warning"

    - name: "Performance"
      description: "Анализ производительности"
      severity: "info"

    - name: "Architecture"
      description: "Проверка архитектурных решений"
      severity: "info"

    - name: "Best Practices"
      description: "Соответствие лучшим практикам"
      severity: "info"

    - name: "ESP32 Compatibility"
      description: "Совместимость с ESP32"
      severity: "warning"

    - name: "Memory Management"
      description: "Управление памятью"
      severity: "warning"

    - name: "Error Handling"
      description: "Обработка ошибок"
      severity: "info"

# Настройки комментариев - НЕОГРАНИЧЕННЫЕ
comments:
  # Все уровни комментариев для максимальной пользы
  level: "all"

  # СТРОГО БЕЗ автоматических исправлений
  auto_fix: false

  # НЕОГРАНИЧЕННОЕ количество комментариев
  max_comments: 0  # 0 = без ограничений

  # Детальные комментарии
  detailed: true

  # Включаем все типы комментариев
  include:
    - "suggestions"
    - "questions"
    - "observations"
    - "improvements"
    - "best_practices"
    - "security_concerns"
    - "performance_tips"
    - "architecture_notes"

# Игнорируемые файлы (только критически важные)
ignore:
  - "*.md"
  - "*.txt"
  - "*.json"
  - "*.yaml"
  - "*.yml"
  - "docs/**"
  - "test/**"
  - "scripts/**"
  - ".github/**"
  - "platformio.ini"
  - "include/version.h"
  - "VERSION"
  - "CHANGELOG.md"
  - "LICENSE"

# Расширенные правила для максимальной пользы
rules:
  - name: "No Breaking Changes"
    description: "Запрет критических изменений"
    severity: "error"

  - name: "Code Style"
    description: "Проверка стиля кода C++17"
    severity: "info"

  - name: "ESP32 Best Practices"
    description: "Лучшие практики для ESP32"
    severity: "info"

  - name: "Memory Safety"
    description: "Безопасность памяти"
    severity: "warning"

  - name: "Error Handling"
    description: "Правильная обработка ошибок"
    severity: "info"

  - name: "Documentation"
    description: "Качество документации кода"
    severity: "info"

  - name: "Modularity"
    description: "Модульность и структура"
    severity: "info"

  - name: "Performance"
    description: "Оптимизация производительности"
    severity: "info"

# Дополнительные настройки для максимальной пользы
settings:
  # Детальный анализ
  analysis_depth: "deep"

  # Включаем все проверки
  enable_all_checks: true

  # Контекстный анализ
  contextual_analysis: true

  # Анализ зависимостей
  dependency_analysis: true

  # Проверка совместимости
  compatibility_check: true
