var searchData=
[
  ['calibrationentry_0',['CalibrationEntry',['../structCalibrationEntry.html',1,'']]],
  ['calibrationmath_1',['CalibrationMath',['../classCalibrationMath.html',1,'']]],
  ['calibrationpoint_2',['CalibrationPoint',['../structCalibrationPoint.html',1,'']]],
  ['calibrationresult_3',['CalibrationResult',['../structCalibrationResult.html',1,'']]],
  ['calibrationstats_4',['CalibrationStats',['../structCalibrationMath_1_1CalibrationStats.html',1,'CalibrationMath']]],
  ['calibrationstorage_5',['CalibrationStorage',['../classCalibrationStorage.html',1,'']]],
  ['calibrationtable_6',['CalibrationTable',['../structCalibrationTable.html',1,'']]],
  ['colorindicators_7',['ColorIndicators',['../structColorIndicators.html',1,'']]],
  ['configdata_8',['ConfigData',['../structConfigData.html',1,'']]],
  ['configvalidationresult_9',['ConfigValidationResult',['../structConfigValidationResult.html',1,'']]],
  ['correctionfactors_10',['CorrectionFactors',['../structCorrectionFactors.html',1,'']]],
  ['correctionpercentages_11',['CorrectionPercentages',['../structCorrectionPercentages.html',1,'']]],
  ['cropcompensationparams_12',['CropCompensationParams',['../structCropCompensationParams.html',1,'']]],
  ['cropconfig_13',['CropConfig',['../structCropConfig.html',1,'']]],
  ['cropeccompensationparams_14',['CropECCompensationParams',['../structCropECCompensationParams.html',1,'']]],
  ['cropparameters_15',['CropParameters',['../structCropParameters.html',1,'']]],
  ['croprecommendationengine_16',['CropRecommendationEngine',['../classCropRecommendationEngine.html',1,'']]]
];
