var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "business", "dir_5e4b16358e46c1f4d6e26fb904c56b9a.html", "dir_5e4b16358e46c1f4d6e26fb904c56b9a" ],
    [ "infrastructure", "dir_4970bdfe28e57c65b6674528293b06cb.html", "dir_4970bdfe28e57c65b6674528293b06cb" ],
    [ "web", "dir_6925d76da2e8d18055a3915854116178.html", "dir_6925d76da2e8d18055a3915854116178" ],
    [ "advanced_calibration_service.h", "advanced__calibration__service_8h.html", null ],
    [ "advanced_filters.h", "advanced__filters_8h.html", "advanced__filters_8h" ],
    [ "basic_sensor_adapter.h", "basic__sensor__adapter_8h.html", "basic__sensor__adapter_8h" ],
    [ "business_services.h", "business__services_8h.html", "business__services_8h" ],
    [ "calibration_data.h", "calibration__data_8h.html", "calibration__data_8h" ],
    [ "calibration_manager.h", "include_2calibration__manager_8h.html", "include_2calibration__manager_8h" ],
    [ "calibration_math.h", "calibration__math_8h.html", "calibration__math_8h" ],
    [ "calibration_storage.h", "calibration__storage_8h.html", "calibration__storage_8h" ],
    [ "debug.h", "debug_8h.html", "debug_8h" ],
    [ "debug_optimized.h", "debug__optimized_8h.html", "debug__optimized_8h" ],
    [ "ISensor.h", "ISensor_8h.html", "ISensor_8h" ],
    [ "jxct_config_vars.h", "jxct__config__vars_8h.html", "jxct__config__vars_8h" ],
    [ "jxct_constants.h", "jxct__constants_8h.html", "jxct__constants_8h" ],
    [ "jxct_device_info.h", "jxct__device__info_8h.html", "jxct__device__info_8h" ],
    [ "jxct_format_utils.h", "jxct__format__utils_8h.html", "jxct__format__utils_8h" ],
    [ "jxct_strings.h", "jxct__strings_8h.html", "jxct__strings_8h" ],
    [ "jxct_ui_system.h", "jxct__ui__system_8h.html", "jxct__ui__system_8h" ],
    [ "logger.h", "logger_8h.html", "logger_8h" ],
    [ "ota_manager.h", "ota__manager_8h.html", "ota__manager_8h" ],
    [ "sensor_calibration_service.h", "include_2sensor__calibration__service_8h.html", "include_2sensor__calibration__service_8h" ],
    [ "sensor_factory.h", "sensor__factory_8h.html", "sensor__factory_8h" ],
    [ "sensor_processing.h", "sensor__processing_8h.html", "sensor__processing_8h" ],
    [ "sensor_types.h", "sensor__types_8h.html", "sensor__types_8h" ],
    [ "validation_utils.h", "validation__utils_8h.html", "validation__utils_8h" ],
    [ "version.h", "version_8h.html", "version_8h" ],
    [ "web_routes.h", "web__routes_8h.html", "web__routes_8h" ]
];